backend:
  name: github
  repo: kstreith/mjsworks
  branch: master

media_folder: "input/assets/paintings" # Folder where user uploaded files should go
public_folder: "assets/paintings"

collections: # A list of collections the CMS should be able to edit
  - name: "painting" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Painting" # Used in the UI, ie.: "New Post"
    folder: "input/paintings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "yml"
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Size", name: "Size", widget: "string"}
      - {label: "Price", name: "Price", widget: "number", valueType: "float"}
      - {label: "Sku", name: "Sku", widget: "string"}
      - {label: "Description", name: "Description", widget: "string"}
      - {label: "For Sale", name: "ForSale", widget: "boolean", default: true}
      - {label: "Sold", name: "Sold", widget: "boolean", required: false}
      - {label: "Image", name: "File", widget: "image"}
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "input/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "Description", widget: "string"}
      - {label: "Lead", name: "Lead", widget: "string"}
      - {label: "Author", name: "Author", widget: "string"}
      - {label: "Published", name: "Published", widget: "datetime", "format": "YYYY-MM-DD" }
      - {label: "Image", name: "Image", widget: "image"}
      - { label: "Text", name: "text", widget: "markdown" }
  - name: "galleries"
    label: "Galleries"
    folder: "input/gallery"
    create: true
    extension: "yml"
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Cover Image", name: "CoverImage", widget: "image" }
      - {label: "Images", name: "Images", widget: "list", fields: [{ label: "Image", name: "Image", widget: "image" }] }
  - name: "galleriesWithDescription"
    label: "Galleries With Description"
    folder: "input/gallery"
    create: true
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Description", name: "body", widget: "markdown" }
      - {label: "Cover Image", name: "CoverImage", widget: "image" }
      - {label: "Images", name: "Images", widget: "list", fields: [{ label: "Image", name: "Image", widget: "image" }] }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "input/index.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }                              
      - label: "Painting Gallery"
        name: "painting"
        file: "input/painting.yml"
        fields:
          - label: "Galleries"
            name: "Galleries"
            widget: "list"
            fields: 
              - { label: "Gallery", name: "Gallery", widget: "string" }
      - label: "About"
        name: "about"
        file: "input/about.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }                              
      - label: "Classes"
        name: "classes"
        file: "input/classes.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }                              
      - label: "Buy"
        name: "buy"
        file: "input/forpurchase.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Navigation Tab", name: "NavigationTab", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }          
      - label: "Shows"
        name: "shows"
        file: "input/shows.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Navigation Tab", name: "NavigationTab", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Faq"
        name: "faq"
        file: "input/faq.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Privacy Policy"
        name: "privacypolicy"
        file: "input/privacyPolicy.md"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }                            
          - { label: "Body", name: "body", widget: "markdown" }          